import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const GeistSans = geistSans;
export const GeistMono = geistMono;

export const metadata = {
  title: 'Clinical Management System',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        {/* Top bar */}
        <div className="bg-white py-2 px-6 text-sm flex justify-end space-x-4 text-gray-700">
          <span>📞 +012 345 6789</span>
          <span>✉ purecare@gmail.com</span>
        </div>

        <div className="border-b border-gray-200"></div>

        {/* Navbar */}
        <nav className="bg-white flex items-center justify-between px-10 py-4 shadow">
          <div className="flex items-center space-x-3">
            <img src="/logo.jpg" alt="PURECARE Logo" className="h-10 w-10" />
            <h1 className="text-5xl font-bold text-blue-500">PURECARE</h1>
          </div>

          <div className="space-x-8 text-black font-bold text-lg">
            <Link href="/" className="hover:text-blue-600">Home</Link>
            <Link href="/about" className="hover:text-blue-600">About</Link>
            <Link href="/service" className="hover:text-blue-600">Service</Link>
            <Link href="/pricing" className="hover:text-blue-600">Pricing</Link>
            <Link href="/staff" className="hover:text-blue-600">Staff</Link>
            <Link href="/contact" className="hover:text-blue-600">Contact</Link>
          </div>
        </nav>

        {/* Page content */}
        {children}
      </body>
    </html>
  );
}